extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended # Uses the recommended rules from @typescript-eslint/eslint-plugin
  - plugin:prettier/recommended # Enables eslint-plugin-prettier and displays prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

settings:
  'import/resolver':
    node: { extensions: ['.js', '.ts'] }

rules:
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/first: 2
  import/newline-after-import: ["error", { count: 1 }]
  # import/no-relative-parent-imports: "error"
  import/order: ["error", {"groups": ["builtin", "external", "internal", "parent", "sibling", "index", "object"], "newlines-between": "always"}]

  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-unused-vars': [2, { args: 'after-used', argsIgnorePattern: '^_' }]